<?php
/**
 * This file is Copyright AltoLabs 2016.
 *
 * @category Mage
 * @package  AltoLabs_Snappic
 * @author   AltoLabs <hi@altolabs.co>
 */

$id = Mage::getModel('altolabs_snappic/connect')->getFacebookId();
if (empty($id) || !Mage::registry('current_product')) {
    return;
}

$productId = 'snappic_' . Mage::registry('current_product')->getId();
?>
<script>
if (typeof fbq !== 'function') {
  !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','//connect.facebook.net/en_US/fbevents.js');
  fbq('init', '<?php echo($id); ?>');
  fbq('track', 'PageView');
}
fbq('track', 'ViewContent', { content_ids: ['<?php echo($productId); ?>'], content_type: 'product' });
</script>
<noscript>
  <img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=<?php echo($id); ?>&ev=PageView&noscript=1" />
</noscript>
